### ISSUE TITLE
Text binding: UpdateSourceTrigger=PropertyChanged does not work

### ISSUE THREAD

**Issue by dkoehler69** [quicoli/WPF-AutoComplete-TextBox#30] opened 2020-09-19 21:13 UTC
The following type of binding does not work:

`Text="{Binding Foo, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"`

The view model is not notified whenever the property changes (ie when the text changes), but only when the AutoCompleteTextBox looses its focus. The later behavior should only apply when `UpdateSourceTrigger=LostFocus`.

**Comment by mitchcapper** [comment] 2021-10-28 19:21
Dupe of #9

**Closed** 2021-11-13 17:59 UTC
